package ChatSystem;


/**
* ChatSystem/_ChatControlStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/ChatControl.idl
* dimanche 7 décembre 2025 20 h 54 GMT+01:00
*/

public class _ChatControlStub extends org.omg.CORBA.portable.ObjectImpl implements ChatSystem.ChatControl
{


  // Authentification et Inscription
  public boolean authentifier (String pseudo, String password)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("authentifier", true);
                $out.write_string (pseudo);
                $out.write_string (password);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return authentifier (pseudo, password        );
            } finally {
                _releaseReply ($in);
            }
  } // authentifier

  public boolean inscrire (String pseudo, String password)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("inscrire", true);
                $out.write_string (pseudo);
                $out.write_string (password);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return inscrire (pseudo, password        );
            } finally {
                _releaseReply ($in);
            }
  } // inscrire


  // Gestion des Salons
  public void creerSalon (String nomSalon, String utilisateur)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("creerSalon", true);
                $out.write_string (nomSalon);
                $out.write_string (utilisateur);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                creerSalon (nomSalon, utilisateur        );
            } finally {
                _releaseReply ($in);
            }
  } // creerSalon

  public String rejoindreSalon (String nomSalon, String utilisateur)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("rejoindreSalon", true);
                $out.write_string (nomSalon);
                $out.write_string (utilisateur);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return rejoindreSalon (nomSalon, utilisateur        );
            } finally {
                _releaseReply ($in);
            }
  } // rejoindreSalon

  public void quitterSalon (String nomSalon, String utilisateur)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("quitterSalon", true);
                $out.write_string (nomSalon);
                $out.write_string (utilisateur);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                quitterSalon (nomSalon, utilisateur        );
            } finally {
                _releaseReply ($in);
            }
  } // quitterSalon

  public String listerSalons ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listerSalons", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listerSalons (        );
            } finally {
                _releaseReply ($in);
            }
  } // listerSalons


  // Nouvelle mÃ©thode pour l'historique
  public String getSalonHistory (String nomSalon)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getSalonHistory", true);
                $out.write_string (nomSalon);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getSalonHistory (nomSalon        );
            } finally {
                _releaseReply ($in);
            }
  } // getSalonHistory

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ChatSystem/ChatControl:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ChatControlStub
