package ChatSystem;


/**
* ChatSystem/ChatControlOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/ChatControl.idl
* dimanche 7 décembre 2025 20 h 54 GMT+01:00
*/

public interface ChatControlOperations 
{

  // Authentification et Inscription
  boolean authentifier (String pseudo, String password);
  boolean inscrire (String pseudo, String password);

  // Gestion des Salons
  void creerSalon (String nomSalon, String utilisateur);
  String rejoindreSalon (String nomSalon, String utilisateur);
  void quitterSalon (String nomSalon, String utilisateur);
  String listerSalons ();

  // Nouvelle mÃ©thode pour l'historique
  String getSalonHistory (String nomSalon);
} // interface ChatControlOperations
