package ChatSystem;


/**
* ChatSystem/ChatControl.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/ChatControl.idl
* dimanche 7 décembre 2025 20 h 54 GMT+01:00
*/

public interface ChatControl extends ChatControlOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatControl
