package ChatSystem;

/**
* ChatSystem/ChatControlHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/ChatControl.idl
* dimanche 7 décembre 2025 20 h 54 GMT+01:00
*/

public final class ChatControlHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatSystem.ChatControl value = null;

  public ChatControlHolder ()
  {
  }

  public ChatControlHolder (ChatSystem.ChatControl initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatSystem.ChatControlHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatSystem.ChatControlHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatSystem.ChatControlHelper.type ();
  }

}
