package ChatSystem;


/**
* ChatSystem/ChatControlPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/ChatControl.idl
* dimanche 7 d�cembre 2025 20 h 54 GMT+01:00
*/

public abstract class ChatControlPOA extends org.omg.PortableServer.Servant
 implements ChatControlOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("authentifier", new Integer (0));
    _methods.put ("inscrire", new Integer (1));
    _methods.put ("creerSalon", new Integer (2));
    _methods.put ("rejoindreSalon", new Integer (3));
    _methods.put ("quitterSalon", new Integer (4));
    _methods.put ("listerSalons", new Integer (5));
    _methods.put ("getSalonHistory", new Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Authentification et Inscription
       case 0:  // ChatSystem/ChatControl/authentifier
       {
         String pseudo = in.read_string ();
         String password = in.read_string ();
         boolean $result = false;
         $result = this.authentifier (pseudo, password);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // ChatSystem/ChatControl/inscrire
       {
         String pseudo = in.read_string ();
         String password = in.read_string ();
         boolean $result = false;
         $result = this.inscrire (pseudo, password);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Gestion des Salons
       case 2:  // ChatSystem/ChatControl/creerSalon
       {
         String nomSalon = in.read_string ();
         String utilisateur = in.read_string ();
         this.creerSalon (nomSalon, utilisateur);
         out = $rh.createReply();
         break;
       }

       case 3:  // ChatSystem/ChatControl/rejoindreSalon
       {
         String nomSalon = in.read_string ();
         String utilisateur = in.read_string ();
         String $result = null;
         $result = this.rejoindreSalon (nomSalon, utilisateur);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ChatSystem/ChatControl/quitterSalon
       {
         String nomSalon = in.read_string ();
         String utilisateur = in.read_string ();
         this.quitterSalon (nomSalon, utilisateur);
         out = $rh.createReply();
         break;
       }

       case 5:  // ChatSystem/ChatControl/listerSalons
       {
         String $result = null;
         $result = this.listerSalons ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // Nouvelle méthode pour l'historique
       case 6:  // ChatSystem/ChatControl/getSalonHistory
       {
         String nomSalon = in.read_string ();
         String $result = null;
         $result = this.getSalonHistory (nomSalon);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ChatSystem/ChatControl:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ChatControl _this() 
  {
    return ChatControlHelper.narrow(
    super._this_object());
  }

  public ChatControl _this(org.omg.CORBA.ORB orb) 
  {
    return ChatControlHelper.narrow(
    super._this_object(orb));
  }


} // class ChatControlPOA
